#:include 'config.fypp'
module calc_hybrid_kernel
  use mod_globals, only : gamma, threshold, threadsE, threadsF, threadsG
  use mod_constant, only : id_slau, over_gamma_1, R_over_gamma_1, one_third, one_sixth, one_twelfth, two_third
  use calc_muscl
  use calc_hybrid
  use libm
  implicit none
  private
  public calc_hybrid_x, calc_hybrid_y, calc_hybrid_z
  real(8), parameter :: one_24        = 1.d0 / 24.d0
  real(8), parameter :: one_48        = 1.d0 / 48.d0
  real(8), parameter :: one_60        = 1.d0 / 60.d0
  real(8), parameter :: one_120       = 1.d0 / 120.d0
  real(8), parameter :: one_240       = 1.d0 / 240.d0
  real(8), parameter :: seven_twelfth = 7.d0 / 12.d0
  integer, parameter :: io            = ${ORDER_IO}$

  #:if ORDER == 6
  integer(8), parameter :: id_acc   = 0_8
  integer(4), parameter :: id_acc4 = 0_4
  integer(2), parameter :: id_acc2 = 0_2
  #:elif ORDER == 4
  integer(4), parameter :: id_acc   = 0_4
  integer(2), parameter :: id_acc2 = 0_2
  #:else
  integer(2), parameter :: id_acc   = 0_2
  #:endif

  interface KEEP
    module procedure KEEP2, KEEP4, KEEP6
  end interface KEEP

  interface SLAU
    module procedure SLAU1, HRSLAU2
  end interface SLAU
contains
  include 'calc_scheme_math.f90'

  attributes(global) subroutine calc_hybrid_x(nx, ny, nz, Q_1, Q_2, Q_3, Q_4, Q_5, T, sensor, E)
    use mod_constant, only : Normal_x
    integer, intent(in), value                :: nx, ny, nz
    real(8), intent(in), device, contiguous   :: Q_1(nx,ny,nz), Q_2(nx,ny,nz), Q_3(nx,ny,nz), Q_4(nx,ny,nz), Q_5(nx,ny,nz), T(nx,ny,nz)
    real(sp), intent(in), device, contiguous  :: sensor(nx,ny,nz)
    real(8), intent(out), device, contiguous  :: E(nx-1,ny-2,nz-2,5)
    integer i, j, k, it, jt, kt, ii, i_base
    integer :: idx, offset_yz
    integer, parameter :: sx = threadsE%x + 2*io + 1
    integer, parameter :: sy = threadsE%y
    integer, parameter :: sz = threadsE%z
    real(8), dimension(-(io-1):sx*sy*sz-io), shared :: rho, u, v, w, p
    real(8)  :: rhol, ul, vl, wl, pl
    real(8)  :: rho_r, u_r, v_r, w_r, p_r
    real(sp) :: fdx
    logical  :: compute_slau
    logical  :: jk_in_range
    it = threadIdx%x
    jt = threadIdx%y
    kt = threadIdx%z
    j  = (blockIdx%y-1)*blockDim%y + jt + 1
    k  = (blockIdx%z-1)*blockDim%z + kt + 1
    i_base = (blockIdx%x-1)*blockDim%x
    offset_yz = (jt-1) * sx + (kt-1) * sx * sy
    jk_in_range = (j >= 1 .and. j <= ny .and. k >= 1 .and. k <= nz)
    do ii = it-io, threadsE%x+io+1, blockDim%x
      i = i_base + ii
      if (i >= 1 .and. i <= nx .and. jk_in_range) then
        idx = ii + offset_yz
        rho(idx) = Q_1(i,j,k); u(idx) = Q_2(i,j,k); v(idx) = Q_3(i,j,k)
        w(idx)   = Q_4(i,j,k); p(idx) = Q_5(i,j,k)
      endif
    enddo
    call syncthreads()
    
    i = (blockIdx%x-1)*blockDim%x + it
    if (nx-1 < i .or. ny-1 < j .or. nz-1 < k) return
    
    fdx = 0.5_sp * (sensor(i,j,k) + sensor(i+1,j,k))
    idx = it + offset_yz
    compute_slau = .false.
    
    #:if ORDER == 6
    if (3 <= i .and. i <= nx-3) then
      if (fdx <= threshold) then
        block
          real(8) :: tmp(6)
          tmp = T(i-2:i+3,j,k)
          associate(uu => u)
            E(i,j-1,k-1,:) = KEEP(id_acc,        rho(idx-2:idx+3), u(idx-2:idx+3), v(idx-2:idx+3), &
                                  w(idx-2:idx+3), uu(idx-2:idx+3), p(idx-2:idx+3), tmp, Normal_x)
          end associate
        end block
      else
        call delta6(fdx, rho(idx-2:idx+3), rhol, rho_r)
        call delta6(fdx,   u(idx-2:idx+3),   ul,   u_r)
        call delta6(fdx,   v(idx-2:idx+3),   vl,   v_r)
        call delta6(fdx,   w(idx-2:idx+3),   wl,   w_r)
        call delta6(fdx,   p(idx-2:idx+3),   pl,   p_r)
        compute_slau = .true.
      endif
    elseif (2 <= i .and. i <= nx-2) then
      if (fdx <= threshold) then
        block
          real(8) :: tmp(4)
          tmp = T(i-1:i+2,j,k)
          associate(uu => u)
            E(i,j-1,k-1,:) = KEEP(id_acc4,       rho(idx-1:idx+2), u(idx-1:idx+2), v(idx-1:idx+2), &
                                  w(idx-1:idx+2), uu(idx-1:idx+2), p(idx-1:idx+2), tmp, Normal_x)
          end associate
        end block
      else
        call delta4(fdx, rho(idx-1:idx+2), rhol, rho_r)
        call delta4(fdx,   u(idx-1:idx+2),   ul,   u_r)
        call delta4(fdx,   v(idx-1:idx+2),   vl,   v_r)
        call delta4(fdx,   w(idx-1:idx+2),   wl,   w_r)
        call delta4(fdx,   p(idx-1:idx+2),   pl,   p_r)
        compute_slau = .true.
      endif
    else
      if (fdx <= threshold) then
        block
          real(8) :: tmp(2)
          tmp = T(i:i+1,j,k)
          associate(uu => u)
            E(i,j-1,k-1,:) = KEEP(id_acc2,     rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                                  w(idx:idx+1), uu(idx:idx+1), p(idx:idx+1), tmp, Normal_x)
          end associate
        end block
      else
        rhol = rho(idx); rho_r = rho(idx+1)
        ul   =   u(idx);   u_r =   u(idx+1)
        vl   =   v(idx);   v_r =   v(idx+1)
        wl   =   w(idx);   w_r =   w(idx+1)
        pl   =   p(idx);   p_r =   p(idx+1)
        compute_slau = .true.
      endif
    endif
    #:elif ORDER == 4
    if (2 <= i .and. i <= nx-2) then
      if (fdx <= threshold) then
        block
          real(8) :: tmp(4)
          tmp = T(i-1:i+2,j,k)
          associate(uu => u)
            E(i,j-1,k-1,:) = KEEP(id_acc,        rho(idx-1:idx+2), u(idx-1:idx+2), v(idx-1:idx+2), &
                                  w(idx-1:idx+2), uu(idx-1:idx+2), p(idx-1:idx+2), tmp, Normal_x)
          end associate
        end block
      else
        call delta4(fdx, rho(idx-1:idx+2), rhol, rho_r)
        call delta4(fdx,   u(idx-1:idx+2),   ul,   u_r)
        call delta4(fdx,   v(idx-1:idx+2),   vl,   v_r)
        call delta4(fdx,   w(idx-1:idx+2),   wl,   w_r)
        call delta4(fdx,   p(idx-1:idx+2),   pl,   p_r)
        compute_slau = .true.
      endif
    else
      if (fdx <= threshold) then
        block
          real(8) :: tmp(2)
          tmp = T(i:i+1,j,k)
          associate(uu => u)
            E(i,j-1,k-1,:) = KEEP(id_acc2,     rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                                  w(idx:idx+1), uu(idx:idx+1), p(idx:idx+1), tmp, Normal_x)
          end associate
        end block
      else
        rhol = rho(idx); rho_r = rho(idx+1)
        ul   =   u(idx);   u_r =   u(idx+1)
        vl   =   v(idx);   v_r =   v(idx+1)
        wl   =   w(idx);   w_r =   w(idx+1)
        pl   =   p(idx);   p_r =   p(idx+1)
        compute_slau = .true.
      endif
    endif
    #:else
    if (fdx <= threshold) then
      block
        real(8) :: tmp(2)
        tmp = T(i:i+1,j,k)
        associate(uu => u)
          E(i,j-1,k-1,:) = KEEP(id_acc,      rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                                w(idx:idx+1), uu(idx:idx+1), p(idx:idx+1), tmp, Normal_x)
        end associate
      end block
    else
      rhol = rho(idx); rho_r = rho(idx+1)
      ul   =   u(idx);   u_r =   u(idx+1)
      vl   =   v(idx);   v_r =   v(idx+1)
      wl   =   w(idx);   w_r =   w(idx+1)
      pl   =   p(idx);   p_r =   p(idx+1)
      compute_slau = .true.
    endif
    #:endif
    
    if (compute_slau) then
      associate(un1 => ul, un2 => u_r)
        call SLAU(id_slau, rhol, rho_r, ul, u_r, vl, v_r, wl, w_r, un1, un2, pl, p_r, Normal_x, 1.0_sp, &
                  E(i,j-1,k-1,1), E(i,j-1,k-1,2), E(i,j-1,k-1,3), E(i,j-1,k-1,4), E(i,j-1,k-1,5))
      end associate
    endif
  end subroutine calc_hybrid_x


  attributes(global) subroutine calc_hybrid_y(nx, ny, nz, Q_1, Q_2, Q_3, Q_4, Q_5, T, sensor, F)
    use mod_constant, only : Normal_y
    integer, intent(in), value                :: nx, ny, nz
    real(8), intent(in), device, contiguous   :: Q_1(nx,ny,nz), Q_2(nx,ny,nz), Q_3(nx,ny,nz), Q_4(nx,ny,nz), Q_5(nx,ny,nz), T(nx,ny,nz)
    real(sp), intent(in), device, contiguous  :: sensor(nx,ny,nz)
    real(8), intent(out), device, contiguous  :: F(nx-2,ny-1,nz-2,5)
    integer i, j, k, it, jt, kt, jj, j_base
    integer :: idx, offset_xz
    integer, parameter :: sx = threadsF%x
    integer, parameter :: sy = threadsF%y + 2*io + 1
    integer, parameter :: sz = threadsF%z
    real(8), dimension(-(io-1):sx*sy*sz-io), shared :: rho, u, v, w, p
    real(8)  :: rhol, ul, vl, wl, pl
    real(8)  :: rho_r, u_r, v_r, w_r, p_r
    real(sp) :: fdy
    logical  :: compute_slau
    logical  :: ik_in_range
    it = threadIdx%x
    jt = threadIdx%y
    kt = threadIdx%z
    i  = (blockIdx%x-1)*blockDim%x + it + 1
    k  = (blockIdx%z-1)*blockDim%z + kt + 1
    j_base = (blockIdx%y-1)*blockDim%y
    offset_xz = (it-1) * sy + (kt-1) * sy * sx
    ik_in_range = (i >= 1 .and. i <= nx .and. k >= 1 .and. k <= nz)
    do jj = jt-io, threadsF%y+io+1, blockDim%y
      j = j_base + jj
      if (ik_in_range .and. j >= 1 .and. j <= ny) then
        idx = jj + offset_xz
        rho(idx) = Q_1(i,j,k); u(idx) = Q_2(i,j,k); v(idx) = Q_3(i,j,k)
        w(idx)   = Q_4(i,j,k); p(idx) = Q_5(i,j,k)
      endif
    enddo
    call syncthreads()
    
    j = (blockIdx%y-1)*blockDim%y + jt
    if (nx-1 < i .or. ny-1 < j .or. nz-1 < k) return
    
    fdy = 0.5_sp * (sensor(i,j,k) + sensor(i,j+1,k))
    idx = jt + offset_xz
    compute_slau = .false.
    
    #:if ORDER == 6
    if (3 <= j .and. j <= ny-3) then
      if (fdy <= threshold) then
        block
          real(8) :: tmp(6)
          tmp = T(i,j-2:j+3,k)
          associate(vv => v)
            F(i-1,j,k-1,:) = KEEP(id_acc,        rho(idx-2:idx+3), u(idx-2:idx+3), v(idx-2:idx+3), &
                                  w(idx-2:idx+3), vv(idx-2:idx+3), p(idx-2:idx+3), tmp, Normal_y)
          end associate
        end block
      else
        call delta6(fdy, rho(idx-2:idx+3), rhol, rho_r)
        call delta6(fdy,   u(idx-2:idx+3),   ul,   u_r)
        call delta6(fdy,   v(idx-2:idx+3),   vl,   v_r)
        call delta6(fdy,   w(idx-2:idx+3),   wl,   w_r)
        call delta6(fdy,   p(idx-2:idx+3),   pl,   p_r)
        compute_slau = .true.
      endif
    elseif (2 <= j .and. j <= ny-2) then
      if (fdy <= threshold) then
        block
          real(8) :: tmp(4)
          tmp = T(i,j-1:j+2,k)
          associate(vv => v)
            F(i-1,j,k-1,:) = KEEP(id_acc4,       rho(idx-1:idx+2), u(idx-1:idx+2), v(idx-1:idx+2), &
                                  w(idx-1:idx+2), vv(idx-1:idx+2), p(idx-1:idx+2), tmp, Normal_y)
          end associate
        end block
      else
        call delta4(fdy, rho(idx-1:idx+2), rhol, rho_r)
        call delta4(fdy,   u(idx-1:idx+2),   ul,   u_r)
        call delta4(fdy,   v(idx-1:idx+2),   vl,   v_r)
        call delta4(fdy,   w(idx-1:idx+2),   wl,   w_r)
        call delta4(fdy,   p(idx-1:idx+2),   pl,   p_r)
        compute_slau = .true.
      endif
    else
      if (fdy <= threshold) then
        block
          real(8) :: tmp(2)
          tmp = T(i,j:j+1,k)
          associate(vv => v)
            F(i-1,j,k-1,:) = KEEP(id_acc2,     rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                                  w(idx:idx+1), vv(idx:idx+1), p(idx:idx+1), tmp, Normal_y)
          end associate
        end block
      else
        rhol = rho(idx); rho_r = rho(idx+1)
        ul   =   u(idx);   u_r =   u(idx+1)
        vl   =   v(idx);   v_r =   v(idx+1)
        wl   =   w(idx);   w_r =   w(idx+1)
        pl   =   p(idx);   p_r =   p(idx+1)
        compute_slau = .true.
      endif
    endif
    #:elif ORDER == 4
    if (2 <= j .and. j <= ny-2) then
      if (fdy <= threshold) then
        block
          real(8) :: tmp(4)
          tmp = T(i,j-1:j+2,k)
          associate(vv => v)
            F(i-1,j,k-1,:) = KEEP(id_acc,        rho(idx-1:idx+2), u(idx-1:idx+2), v(idx-1:idx+2), &
                                  w(idx-1:idx+2), vv(idx-1:idx+2), p(idx-1:idx+2), tmp, Normal_y)
          end associate
        end block
      else
        call delta4(fdy, rho(idx-1:idx+2), rhol, rho_r)
        call delta4(fdy,   u(idx-1:idx+2),   ul,   u_r)
        call delta4(fdy,   v(idx-1:idx+2),   vl,   v_r)
        call delta4(fdy,   w(idx-1:idx+2),   wl,   w_r)
        call delta4(fdy,   p(idx-1:idx+2),   pl,   p_r)
        compute_slau = .true.
      endif
    else
      if (fdy <= threshold) then
        block
          real(8) :: tmp(2)
          tmp = T(i,j:j+1,k)
          associate(vv => v)
            F(i-1,j,k-1,:) = KEEP(id_acc2,     rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                                  w(idx:idx+1), vv(idx:idx+1), p(idx:idx+1), tmp, Normal_y)
          end associate
        end block
      else
        rhol = rho(idx); rho_r = rho(idx+1)
        ul   =   u(idx);   u_r =   u(idx+1)
        vl   =   v(idx);   v_r =   v(idx+1)
        wl   =   w(idx);   w_r =   w(idx+1)
        pl   =   p(idx);   p_r =   p(idx+1)
        compute_slau = .true.
      endif
    endif
    #:else
    if (fdy <= threshold) then
      block
        real(8) :: tmp(2)
        tmp = T(i,j:j+1,k)
        associate(vv => v)
          F(i-1,j,k-1,:) = KEEP(id_acc,      rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                                w(idx:idx+1), vv(idx:idx+1), p(idx:idx+1), tmp, Normal_y)
        end associate
      end block
    else
      rhol = rho(idx); rho_r = rho(idx+1)
      ul   =   u(idx);   u_r =   u(idx+1)
      vl   =   v(idx);   v_r =   v(idx+1)
      wl   =   w(idx);   w_r =   w(idx+1)
      pl   =   p(idx);   p_r =   p(idx+1)
      compute_slau = .true.
    endif
    #:endif
    
    if (compute_slau) then
      associate(un1 => vl, un2 => v_r)
        call SLAU(id_slau, rhol, rho_r, ul, u_r, vl, v_r, wl, w_r, un1, un2, pl, p_r, Normal_y, 1.0_sp, &
                  F(i-1,j,k-1,1), F(i-1,j,k-1,2), F(i-1,j,k-1,3), F(i-1,j,k-1,4), F(i-1,j,k-1,5))
      end associate
    endif
  end subroutine calc_hybrid_y


  attributes(global) subroutine calc_hybrid_z(nx, ny, nz, Q_1, Q_2, Q_3, Q_4, Q_5, T, sensor, G)
    use mod_constant, only : Normal_z
    integer, intent(in), value                :: nx, ny, nz
    real(8), intent(in), device, contiguous   :: Q_1(nx,ny,nz), Q_2(nx,ny,nz), Q_3(nx,ny,nz), Q_4(nx,ny,nz), Q_5(nx,ny,nz), T(nx,ny,nz)
    real(sp), intent(in), device, contiguous  :: sensor(nx,ny,nz)
    real(8), intent(out), device, contiguous  :: G(nx-2,ny-2,nz-1,5)
    integer i, j, k, it, jt, kt, kk, k_base
    integer :: idx, offset_xy
    integer, parameter :: sx = threadsG%x
    integer, parameter :: sy = threadsG%y
    integer, parameter :: sz = threadsG%z + 2*io + 1
    real(8), dimension(-(io-1):sx*sy*sz-io), shared :: rho, u, v, w, p
    real(8)  :: rhol, ul, vl, wl, pl
    real(8)  :: rho_r, u_r, v_r, w_r, p_r
    real(sp) :: fdz
    logical  :: compute_slau
    logical  :: ij_in_range
    it = threadIdx%x
    jt = threadIdx%y
    kt = threadIdx%z
    i  = (blockIdx%x-1)*blockDim%x + it + 1
    j  = (blockIdx%y-1)*blockDim%y + jt + 1
    k_base = (blockIdx%z-1)*blockDim%z
    offset_xy = (jt-1) * sz + (it-1) * sz * sy
    ij_in_range = (i >= 1 .and. i <= nx .and. j >= 1 .and. j <= ny)
    do kk = kt-io, threadsG%z+io+1, blockDim%z
      k = k_base + kk
      if (ij_in_range .and. k >= 1 .and. k <= nz) then
        idx = kk + offset_xy
        rho(idx) = Q_1(i,j,k); u(idx) = Q_2(i,j,k); v(idx) = Q_3(i,j,k)
        w(idx)   = Q_4(i,j,k); p(idx) = Q_5(i,j,k)
      endif
    enddo
    call syncthreads()
    
    k = (blockIdx%z-1)*blockDim%z + kt
    if (nx-1 < i .or. ny-1 < j .or. nz-1 < k) return
    
    fdz = 0.5_sp * (sensor(i,j,k) + sensor(i,j,k+1))
    idx = kt + offset_xy
    compute_slau = .false.
    
    #:if ORDER == 6
    if (3 <= k .and. k <= nz-3) then
      if (fdz <= threshold) then
        block
          real(8) :: tmp(6)
          tmp = T(i,j,k-2:k+3)
          associate(ww => w)
            G(i-1,j-1,k,:) = KEEP(id_acc,        rho(idx-2:idx+3), u(idx-2:idx+3), v(idx-2:idx+3), &
                                  w(idx-2:idx+3), ww(idx-2:idx+3), p(idx-2:idx+3), tmp, Normal_z)
          end associate
        end block
      else
        call delta6(fdz, rho(idx-2:idx+3), rhol, rho_r)
        call delta6(fdz,   u(idx-2:idx+3),   ul,   u_r)
        call delta6(fdz,   v(idx-2:idx+3),   vl,   v_r)
        call delta6(fdz,   w(idx-2:idx+3),   wl,   w_r)
        call delta6(fdz,   p(idx-2:idx+3),   pl,   p_r)
        compute_slau = .true.
      endif
    elseif (2 <= k .and. k <= nz-2) then
      if (fdz <= threshold) then
        block
          real(8) :: tmp(4)
          tmp = T(i,j,k-1:k+2)
          associate(ww => w)
            G(i-1,j-1,k,:) = KEEP(id_acc4,       rho(idx-1:idx+2), u(idx-1:idx+2), v(idx-1:idx+2), &
                                  w(idx-1:idx+2), ww(idx-1:idx+2), p(idx-1:idx+2), tmp, Normal_z)
          end associate
        end block
      else
        call delta4(fdz, rho(idx-1:idx+2), rhol, rho_r)
        call delta4(fdz,   u(idx-1:idx+2),   ul,   u_r)
        call delta4(fdz,   v(idx-1:idx+2),   vl,   v_r)
        call delta4(fdz,   w(idx-1:idx+2),   wl,   w_r)
        call delta4(fdz,   p(idx-1:idx+2),   pl,   p_r)
        compute_slau = .true.
      endif
    else
      if (fdz <= threshold) then
        block
          real(8) :: tmp(2)
          tmp = T(i,j,k:k+1)
          associate(ww => w)
            G(i-1,j-1,k,:) = KEEP(id_acc2,     rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                                  w(idx:idx+1), ww(idx:idx+1), p(idx:idx+1), tmp, Normal_z)
          end associate
        end block
      else
        rhol = rho(idx); rho_r = rho(idx+1)
        ul   =   u(idx);   u_r =   u(idx+1)
        vl   =   v(idx);   v_r =   v(idx+1)
        wl   =   w(idx);   w_r =   w(idx+1)
        pl   =   p(idx);   p_r =   p(idx+1)
        compute_slau = .true.
      endif
    endif
    #:elif ORDER == 4
    if (2 <= k .and. k <= nz-2) then
      if (fdz <= threshold) then
        block
          real(8) :: tmp(4)
          tmp = T(i,j,k-1:k+2)
          associate(ww => w)
            G(i-1,j-1,k,:) = KEEP(id_acc,        rho(idx-1:idx+2), u(idx-1:idx+2), v(idx-1:idx+2), &
                                  w(idx-1:idx+2), ww(idx-1:idx+2), p(idx-1:idx+2), tmp, Normal_z)
          end associate
        end block
      else
        call delta4(fdz, rho(idx-1:idx+2), rhol, rho_r)
        call delta4(fdz,   u(idx-1:idx+2),   ul,   u_r)
        call delta4(fdz,   v(idx-1:idx+2),   vl,   v_r)
        call delta4(fdz,   w(idx-1:idx+2),   wl,   w_r)
        call delta4(fdz,   p(idx-1:idx+2),   pl,   p_r)
        compute_slau = .true.
      endif
    else
      if (fdz <= threshold) then
        block
          real(8) :: tmp(2)
          tmp = T(i,j,k:k+1)
          associate(ww => w)
            G(i-1,j-1,k,:) = KEEP(id_acc2,     rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                                  w(idx:idx+1), ww(idx:idx+1), p(idx:idx+1), tmp, Normal_z)
          end associate
        end block
      else
        rhol = rho(idx); rho_r = rho(idx+1)
        ul   =   u(idx);   u_r =   u(idx+1)
        vl   =   v(idx);   v_r =   v(idx+1)
        wl   =   w(idx);   w_r =   w(idx+1)
        pl   =   p(idx);   p_r =   p(idx+1)
        compute_slau = .true.
      endif
    endif
    #:else
    if (fdz <= threshold) then
      block
        real(8) :: tmp(2)
        tmp = T(i,j,k:k+1)
        associate(ww => w)
          G(i-1,j-1,k,:) = KEEP(id_acc,      rho(idx:idx+1), u(idx:idx+1), v(idx:idx+1), &
                                w(idx:idx+1), ww(idx:idx+1), p(idx:idx+1), tmp, Normal_z)
        end associate
      end block
    else
      rhol = rho(idx); rho_r = rho(idx+1)
      ul   =   u(idx);   u_r =   u(idx+1)
      vl   =   v(idx);   v_r =   v(idx+1)
      wl   =   w(idx);   w_r =   w(idx+1)
      pl   =   p(idx);   p_r =   p(idx+1)
      compute_slau = .true.
    endif
    #:endif
    
    if (compute_slau) then
      associate(un1 => wl, un2 => w_r)
        call SLAU(id_slau, rhol, rho_r, ul, u_r, vl, v_r, wl, w_r, un1, un2, pl, p_r, Normal_z, 1.0_sp, &
                  G(i-1,j-1,k,1), G(i-1,j-1,k,2), G(i-1,j-1,k,3), G(i-1,j-1,k,4), G(i-1,j-1,k,5))
      end associate
    endif
  end subroutine calc_hybrid_z
end module calc_hybrid_kernel
