#:include 'config.fypp'
module calc_keep_kernel_internal
  use mod_globals, only : threadsE, threadsF, threadsG
  use mod_constant, only : R_over_gamma_1, one_third, one_sixth, one_twelfth, two_third
  use libm
  implicit none
  private
  public calc_keep_x_in, calc_keep_y_in, calc_keep_z_in, calc_keep_z_in_koff
  real(8), parameter :: one_24        = 1.d0 / 24.d0
  real(8), parameter :: one_48        = 1.d0 / 48.d0
  real(8), parameter :: one_60        = 1.d0 / 60.d0
  real(8), parameter :: one_120       = 1.d0 / 120.d0
  real(8), parameter :: one_240       = 1.d0 / 240.d0
  real(8), parameter :: seven_twelfth = 7.d0 / 12.d0
  integer, parameter :: io = ${ORDER_IO}$

#:if ORDER == 6
  integer(8), parameter :: id_acc = 0_8
#:elif ORDER == 4
  integer(4), parameter :: id_acc = 0_4
#:else
  integer(2), parameter :: id_acc = 0_2
#:endif

  interface KEEP
    module procedure KEEP2, KEEP4, KEEP6
  end interface KEEP
contains
  include 'calc_keep_3d.f90'

  attributes(global) subroutine calc_keep_x_in(nx, ny, nz, Q_1, Q_2, Q_3, Q_4, Q_5, T, E)
    use mod_constant, only : Normal_x
    integer, intent(in), value                :: nx, ny, nz
    real(8), intent(in), device, contiguous   :: Q_1(nx,ny,nz), Q_2(nx,ny,nz), Q_3(nx,ny,nz), Q_4(nx,ny,nz), Q_5(nx,ny,nz), T(nx,ny,nz)
    real(8), intent(out), device, contiguous  :: E(nx-1,ny-2,nz-2,5)
    integer i, j, k, it, jt, kt
    integer :: ii, i_base, idx, offset_yz
    logical :: jk_in_range
    integer, parameter :: sx = threadsE%x + 2*io + 1
    integer, parameter :: sy = threadsE%y
    integer, parameter :: sz = threadsE%z
    real(8), dimension(-(io-1):sx*sy*sz-io), shared :: rho, u, v, w, p, tmp
    it = threadIdx%x
    jt = threadIdx%y
    kt = threadIdx%z
    j  = (blockIdx%y-1)*blockDim%y + jt + 1
    k  = (blockIdx%z-1)*blockDim%z + kt + 1
    i_base = (blockIdx%x-1)*blockDim%x
    offset_yz = (jt-1) * sx + (kt-1) * sx * sy
    jk_in_range = (j >= 1 .and. j <= ny .and. k >= 1 .and. k <= nz)
    do ii = it-io, threadsE%x+io+1, blockDim%x
      i = i_base + ii
      if (i >= 1 .and. i <= nx .and. jk_in_range) then
        idx = ii + offset_yz
        rho(idx) = Q_1(i,j,k);   u(idx) = Q_2(i,j,k)
          v(idx) = Q_3(i,j,k);   w(idx) = Q_4(i,j,k)
          p(idx) = Q_5(i,j,k); tmp(idx) =   T(i,j,k)
      endif
    enddo
    call syncthreads()
    i = (blockIdx%x-1)*blockDim%x + it
    if (io+1 <= i .and. i <= nx-(io+1) .and. j <= ny-1 .and. k <= nz-1) then
      associate(uu => u)
      idx = it + offset_yz
      E(i,j-1,k-1,:) = KEEP(id_acc, &
                            rho(idx-io:idx+io+1), u(idx-io:idx+io+1), &
                              v(idx-io:idx+io+1), w(idx-io:idx+io+1), &
                             uu(idx-io:idx+io+1), p(idx-io:idx+io+1), &
                            tmp(idx-io:idx+io+1), Normal_x)
      end associate
    endif
  end subroutine calc_keep_x_in


  attributes(global) subroutine calc_keep_y_in(nx, ny, nz, Q_1, Q_2, Q_3, Q_4, Q_5, T, F)
    use mod_constant, only : Normal_y
    integer, intent(in), value                :: nx, ny, nz
    real(8), intent(in), device, contiguous   :: Q_1(nx,ny,nz), Q_2(nx,ny,nz), Q_3(nx,ny,nz), Q_4(nx,ny,nz), Q_5(nx,ny,nz), T(nx,ny,nz)
    real(8), intent(out), device, contiguous  :: F(nx-2,ny-1,nz-2,5)
    integer i, j, k, it, jt, kt
    integer :: jj, j_base, idx, offset_xz
    logical :: ik_in_range
    integer, parameter :: sx = threadsF%x
    integer, parameter :: sy = threadsF%y + 2*io + 1
    integer, parameter :: sz = threadsF%z
    real(8), dimension(-(io-1):sx*sy*sz-io), shared :: rho, u, v, w, p, tmp
    it = threadIdx%x
    jt = threadIdx%y
    kt = threadIdx%z
    i  = (blockIdx%x-1)*blockDim%x + it + 1
    k  = (blockIdx%z-1)*blockDim%z + kt + 1
    j_base = (blockIdx%y-1)*blockDim%y
    offset_xz = (it-1) * sy + (kt-1) * sy * sx
    ik_in_range = (i >= 1 .and. i <= nx .and. k >= 1 .and. k <= nz)
    do jj = jt-io, threadsF%y+io+1, blockDim%y
      j = j_base + jj
      if (ik_in_range .and. j >= 1 .and. j <= ny) then
        idx = jj + offset_xz
        rho(idx) = Q_1(i,j,k);   u(idx) = Q_2(i,j,k)
          v(idx) = Q_3(i,j,k);   w(idx) = Q_4(i,j,k)
          p(idx) = Q_5(i,j,k); tmp(idx) =   T(i,j,k)
      endif
    enddo
    call syncthreads()
    j = (blockIdx%y-1)*blockDim%y + jt
    if (io+1 <= j .and. j <= ny-(io+1) .and. i <= nx-1 .and. k <= nz-1) then
      associate(vv => v)
      idx = jt + offset_xz
      F(i-1,j,k-1,:) = KEEP(id_acc, &
                            rho(idx-io:idx+io+1), u(idx-io:idx+io+1), &
                              v(idx-io:idx+io+1), w(idx-io:idx+io+1), &
                             vv(idx-io:idx+io+1), p(idx-io:idx+io+1), &
                            tmp(idx-io:idx+io+1), Normal_y)
      end associate
    endif
  end subroutine calc_keep_y_in


  attributes(global) subroutine calc_keep_z_in(nx, ny, nz, Q_1, Q_2, Q_3, Q_4, Q_5, T, G)
    use mod_constant, only : Normal_z
    integer, intent(in), value                :: nx, ny, nz
    real(8), intent(in), device, contiguous   :: Q_1(nx,ny,nz), Q_2(nx,ny,nz), Q_3(nx,ny,nz), Q_4(nx,ny,nz), Q_5(nx,ny,nz), T(nx,ny,nz)
    real(8), intent(out), device, contiguous  :: G(nx-2,ny-2,nz-1,5)
    integer i, j, k, it, jt, kt
    integer :: kk, k_base, idx, offset_xy
    logical :: ij_in_range
    integer, parameter :: sx = threadsG%x
    integer, parameter :: sy = threadsG%y
    integer, parameter :: sz = threadsG%z + 2*io + 1
    real(8), dimension(-(io-1):sx*sy*sz-io), shared :: rho, u, v, w, p, tmp
    it = threadIdx%x
    jt = threadIdx%y
    kt = threadIdx%z
    i  = (blockIdx%x-1)*blockDim%x + it + 1
    j  = (blockIdx%y-1)*blockDim%y + jt + 1
    k_base = (blockIdx%z-1)*blockDim%z
    offset_xy = (jt-1) * sz + (it-1) * sz * sy
    ij_in_range = (i >= 1 .and. i <= nx .and. j >= 1 .and. j <= ny)
    do kk = kt-io, threadsG%z+io+1, blockDim%z
      k = k_base + kk
      if (ij_in_range .and. k >= 1 .and. k <= nz) then
        idx = kk + offset_xy
        rho(idx) = Q_1(i,j,k);   u(idx) = Q_2(i,j,k)
          v(idx) = Q_3(i,j,k);   w(idx) = Q_4(i,j,k)
          p(idx) = Q_5(i,j,k); tmp(idx) =   T(i,j,k)
      endif
    enddo
    call syncthreads()
    k = (blockIdx%z-1)*blockDim%z + kt
    if (io+1 <= k .and. k <= nz-(io+1) .and. i <= nx-1 .and. j <= ny-1) then
      associate(ww => w)
      idx = kt + offset_xy
      G(i-1,j-1,k,:) = KEEP(id_acc, &
                            rho(idx-io:idx+io+1), u(idx-io:idx+io+1), &
                              v(idx-io:idx+io+1), w(idx-io:idx+io+1), &
                             ww(idx-io:idx+io+1), p(idx-io:idx+io+1), &
                            tmp(idx-io:idx+io+1), Normal_z)
      end associate
    endif
  end subroutine calc_keep_z_in


  attributes(global) subroutine calc_keep_z_in_koff(nx, ny, nz, Q_1, Q_2, Q_3, Q_4, Q_5, T, G, k_lo, k_hi)
    use mod_constant, only : Normal_z
    integer, intent(in), value                :: nx, ny, nz, k_lo, k_hi
    real(8), intent(in), device, contiguous   :: Q_1(nx,ny,nz), Q_2(nx,ny,nz), Q_3(nx,ny,nz), Q_4(nx,ny,nz), Q_5(nx,ny,nz), T(nx,ny,nz)
    real(8), intent(inout), device, contiguous :: G(nx-2,ny-2,nz-1,5)
    integer i, j, k, it, jt, kt
    integer :: kk, k_base, idx, offset_xy
    logical :: ij_in_range
    integer, parameter :: sx = threadsG%x
    integer, parameter :: sy = threadsG%y
    integer, parameter :: sz = threadsG%z + 2*io + 1
    real(8), dimension(-(io-1):sx*sy*sz-io), shared :: rho, u, v, w, p, tmp
    it = threadIdx%x
    jt = threadIdx%y
    kt = threadIdx%z
    i  = (blockIdx%x-1)*blockDim%x + it + 1
    j  = (blockIdx%y-1)*blockDim%y + jt + 1
    k_base = (blockIdx%z-1)*blockDim%z + k_lo - 1
    offset_xy = (jt-1) * sz + (it-1) * sz * sy
    ij_in_range = (i >= 1 .and. i <= nx .and. j >= 1 .and. j <= ny)
    do kk = kt-io, threadsG%z+io+1, blockDim%z
      k = k_base + kk
      if (ij_in_range .and. k >= 1 .and. k <= nz) then
        idx = kk + offset_xy
        rho(idx) = Q_1(i,j,k);   u(idx) = Q_2(i,j,k)
          v(idx) = Q_3(i,j,k);   w(idx) = Q_4(i,j,k)
          p(idx) = Q_5(i,j,k); tmp(idx) =   T(i,j,k)
      endif
    enddo
    call syncthreads()
    k = k_base + kt
    if (k_lo <= k .and. k <= k_hi .and. i <= nx-1 .and. j <= ny-1) then
      associate(ww => w)
      idx = kt + offset_xy
      G(i-1,j-1,k,:) = KEEP(id_acc, &
                            rho(idx-io:idx+io+1), u(idx-io:idx+io+1), &
                              v(idx-io:idx+io+1), w(idx-io:idx+io+1), &
                             ww(idx-io:idx+io+1), p(idx-io:idx+io+1), &
                            tmp(idx-io:idx+io+1), Normal_z)
      end associate
    endif
  end subroutine calc_keep_z_in_koff
end module calc_keep_kernel_internal
