#:include 'config.fypp'
module calc_keep_kernel
  use mod_globals, only : gamma, threadsE, threadsF
  use mod_constant, only : R_over_gamma_1, one_third, one_sixth, one_twelfth, two_third
  use libm
  implicit none
  private
  public calc_keep_x, calc_keep_y
  real(8), parameter :: one_24        = 1.d0 / 24.d0
  real(8), parameter :: one_48        = 1.d0 / 48.d0
  real(8), parameter :: one_60        = 1.d0 / 60.d0
  real(8), parameter :: one_120       = 1.d0 / 120.d0
  real(8), parameter :: one_240       = 1.d0 / 240.d0
  real(8), parameter :: seven_twelfth = 7.d0 / 12.d0
  integer, parameter :: io            = ${ORDER_IO}$
  #:if ORDER == 6
  integer(8), parameter :: id_acc   = 0_8
  integer(4), parameter :: id_acc4 = 0_4
  integer(2), parameter :: id_acc2 = 0_2
  #:elif ORDER == 4
  integer(4), parameter :: id_acc   = 0_4
  integer(2), parameter :: id_acc2 = 0_2
  #:else
  integer(2), parameter :: id_acc   = 0_2
  #:endif

  interface KEEP
    module procedure KEEP2, KEEP4, KEEP6
  end interface KEEP
contains
  include 'calc_scheme_math.f90'

  attributes(global) subroutine calc_keep_x(nx, ny, Q_1, Q_2, Q_3, Q_4, T, E)
    use mod_constant, only : Normal_x
    integer, intent(in), value                :: nx, ny
    real(8), intent(in), device, contiguous   :: Q_1(nx,ny), Q_2(nx,ny), Q_3(nx,ny), Q_4(nx,ny), T(nx,ny)
    real(8), intent(out), device, contiguous  :: E(nx-1,ny-2,4)
    integer i, j, it, jt
    integer :: ii, i_base, idx, offset_y
    integer, parameter :: sx = threadsE%x + 2*io + 1
    integer, parameter :: sy = threadsE%y
    real(8), dimension(-(io-1):sx*sy-io), shared :: rho, u, v, p, tmp
    it = threadIdx%x
    jt = threadIdx%y
    j  = (blockIdx%y-1)*blockDim%y + jt + 1
    i_base = (blockIdx%x-1)*blockDim%x
    offset_y = (jt-1) * sx
    do ii = it-io, threadsE%x+io+1, blockDim%x
      i = i_base + ii
      if (i >= 1 .and. i <= nx .and. j >= 1 .and. j <= ny) then
        idx = ii + offset_y
        rho(idx) = Q_1(i,j); u(idx) = Q_2(i,j)
          v(idx) = Q_3(i,j); p(idx) = Q_4(i,j); tmp(idx) = T(i,j)
      endif
    enddo
    call syncthreads()
    i = (blockIdx%x-1)*blockDim%x + it
    if (nx-1 < i .or. ny-1 < j) return
    idx = it + offset_y
    associate(uu => u)
    #:if ORDER == 6
    if (3 <= i .and. i <= nx-3) then
      E(i,j-1,:) = KEEP(id_acc,        rho(idx-2:idx+3), u(idx-2:idx+3),   v(idx-2:idx+3), &
                        uu(idx-2:idx+3), p(idx-2:idx+3), tmp(idx-2:idx+3), Normal_x)
    elseif (2 <= i .and. i <= nx-2) then
      E(i,j-1,:) = KEEP(id_acc4,       rho(idx-1:idx+2), u(idx-1:idx+2),   v(idx-1:idx+2), &
                        uu(idx-1:idx+2), p(idx-1:idx+2), tmp(idx-1:idx+2), Normal_x)
    else
      E(i,j-1,:) = KEEP(id_acc2,       rho(idx:idx+1),   u(idx:idx+1),     v(idx:idx+1), &
                        uu(idx:idx+1),   p(idx:idx+1),   tmp(idx:idx+1),   Normal_x)
    endif
    #:elif ORDER == 4
    if (2 <= i .and. i <= nx-2) then
      E(i,j-1,:) = KEEP(id_acc,        rho(idx-1:idx+2), u(idx-1:idx+2),   v(idx-1:idx+2), &
                        uu(idx-1:idx+2), p(idx-1:idx+2), tmp(idx-1:idx+2), Normal_x)
    else
      E(i,j-1,:) = KEEP(id_acc2,       rho(idx:idx+1),   u(idx:idx+1),     v(idx:idx+1), &
                        uu(idx:idx+1),   p(idx:idx+1),   tmp(idx:idx+1),   Normal_x)
    endif
    #:else
      E(i,j-1,:) = KEEP(id_acc,        rho(idx:idx+1),   u(idx:idx+1),     v(idx:idx+1), &
                        uu(idx:idx+1),   p(idx:idx+1),   tmp(idx:idx+1),   Normal_x)
    #:endif
    end associate
  end subroutine calc_keep_x


  attributes(global) subroutine calc_keep_y(nx, ny, Q_1, Q_2, Q_3, Q_4, T, F)
    use mod_constant, only : Normal_y
    integer, intent(in), value                :: nx, ny
    real(8), intent(in), device, contiguous   :: Q_1(nx,ny), Q_2(nx,ny), Q_3(nx,ny), Q_4(nx,ny), T(nx,ny)
    real(8), intent(out), device, contiguous  :: F(nx-2,ny-1,4)
    integer i, j, it, jt
    integer :: jj, j_base, idx, offset_x
    integer, parameter :: sx = threadsF%x
    integer, parameter :: sy = threadsF%y + 2*io + 1
    real(8), dimension(-(io-1):sx*sy-io), shared :: rho, u, v, p, tmp
    it = threadIdx%x
    jt = threadIdx%y
    i  = (blockIdx%x-1)*blockDim%x + it + 1
    j_base = (blockIdx%y-1)*blockDim%y
    offset_x = (it-1) * sy
    do jj = jt-io, threadsF%y+io+1, blockDim%y
      j = j_base + jj
      if (i >= 1 .and. i <= nx .and. j >= 1 .and. j <= ny) then
        idx = jj + offset_x
        rho(idx) = Q_1(i,j); u(idx) = Q_2(i,j)
          v(idx) = Q_3(i,j); p(idx) = Q_4(i,j); tmp(idx) = T(i,j)
      endif
    enddo
    call syncthreads()
    j = (blockIdx%y-1)*blockDim%y + jt
    if (nx-1 < i .or. ny-1 < j) return
    idx = jt + offset_x
    associate(vv => v)
    #:if ORDER == 6
    if (3 <= j .and. j <= ny-3) then
      F(i-1,j,:) = KEEP(id_acc,        rho(idx-2:idx+3), u(idx-2:idx+3),   v(idx-2:idx+3), &
                        vv(idx-2:idx+3), p(idx-2:idx+3), tmp(idx-2:idx+3), Normal_y)
    elseif (2 <= j .and. j <= ny-2) then
      F(i-1,j,:) = KEEP(id_acc4,       rho(idx-1:idx+2), u(idx-1:idx+2),   v(idx-1:idx+2), &
                        vv(idx-1:idx+2), p(idx-1:idx+2), tmp(idx-1:idx+2), Normal_y)
    else
      F(i-1,j,:) = KEEP(id_acc2,       rho(idx:idx+1),   u(idx:idx+1),     v(idx:idx+1),   &
                        vv(idx:idx+1),   p(idx:idx+1),   tmp(idx:idx+1),   Normal_y)
    endif
    #:elif ORDER == 4
    if (2 <= j .and. j <= ny-2) then
      F(i-1,j,:) = KEEP(id_acc,        rho(idx-1:idx+2), u(idx-1:idx+2),   v(idx-1:idx+2), &
                        vv(idx-1:idx+2), p(idx-1:idx+2), tmp(idx-1:idx+2), Normal_y)
    else
      F(i-1,j,:) = KEEP(id_acc2,       rho(idx:idx+1),   u(idx:idx+1),     v(idx:idx+1),   &
                        vv(idx:idx+1),   p(idx:idx+1),   tmp(idx:idx+1),   Normal_y)
    endif
    #:else
      F(i-1,j,:) = KEEP(id_acc,        rho(idx:idx+1),   u(idx:idx+1),     v(idx:idx+1),   &
                        vv(idx:idx+1),   p(idx:idx+1),   tmp(idx:idx+1),   Normal_y)
    #:endif
    end associate
  end subroutine calc_keep_y
end module calc_keep_kernel
