#:include 'config.fypp'
module calc_keep_kernel_internal
  use mod_globals, only : threadsE, threadsF
  use mod_constant, only : R_over_gamma_1, one_third, one_sixth, one_twelfth, two_third
  use libm
  implicit none
  private
  public calc_keep_x_in, calc_keep_y_in
  real(8), parameter :: one_24        = 1.d0 / 24.d0
  real(8), parameter :: one_48        = 1.d0 / 48.d0
  real(8), parameter :: one_60        = 1.d0 / 60.d0
  real(8), parameter :: one_120       = 1.d0 / 120.d0
  real(8), parameter :: one_240       = 1.d0 / 240.d0
  real(8), parameter :: seven_twelfth = 7.d0 / 12.d0
  integer, parameter :: io = ${ORDER_IO}$

#:if ORDER == 6
  integer(8), parameter :: id_acc = 0_8
#:elif ORDER == 4
  integer(4), parameter :: id_acc = 0_4
#:else
  integer(2), parameter :: id_acc = 0_2
#:endif

  interface KEEP
    module procedure KEEP2, KEEP4, KEEP6
  end interface KEEP
contains
  include 'calc_keep_2d.f90'

  attributes(global) subroutine calc_keep_x_in(nx, ny, Q, T, E)
    use mod_constant, only : Normal_x
    integer, intent(in), value                :: nx, ny
    real(8), intent(in), device, contiguous   :: Q(nx,4,ny), T(nx,ny)
    real(8), intent(out), device, contiguous  :: E(4,nx-1,ny-2)
    integer i, j, it, jt
    integer :: ii, i_base, idx, offset_y
    integer, parameter :: sx = threadsE%x + 2*io + 1
    integer, parameter :: sy = threadsE%y
    real(8), dimension(-(io-1):sx*sy-io), shared :: rho, u, v, p, tmp
    it = threadIdx%x
    jt = threadIdx%y
    j  = (blockIdx%y-1)*blockDim%y + jt + 1
    i_base = (blockIdx%x-1)*blockDim%x
    offset_y = (jt-1) * sx
    do ii = it-io, threadsE%x+io+1, blockDim%x
      i = i_base + ii
      if (i >= 1 .and. i <= nx .and. j >= 1 .and. j <= ny) then
        idx = ii + offset_y
        rho(idx) = Q(i,1,j); u(idx) = Q(i,2,j)
          v(idx) = Q(i,3,j); p(idx) = Q(i,4,j); tmp(idx) = T(i,j)
      endif
    enddo
    call syncthreads()
    i = (blockIdx%x-1)*blockDim%x + it
    if (io+1 <= i .and. i <= nx-(io+1) .and. j <= ny-1) then
      associate(uu => u)
      idx = it + offset_y
      E(:,i,j-1) = KEEP(id_acc, &
                        rho(idx-io:idx+io+1), u(idx-io:idx+io+1), &
                          v(idx-io:idx+io+1), &
                         uu(idx-io:idx+io+1), p(idx-io:idx+io+1), &
                        tmp(idx-io:idx+io+1), Normal_x)
      end associate
    endif
  end subroutine calc_keep_x_in


  attributes(global) subroutine calc_keep_y_in(nx, ny, Q, T, F)
    use mod_constant, only : Normal_y
    integer, intent(in), value                :: nx, ny
    real(8), intent(in), device, contiguous   :: Q(nx,4,ny), T(nx,ny)
    real(8), intent(out), device, contiguous  :: F(4,nx-2,ny-1)
    integer i, j, it, jt
    integer :: jj, j_base, idx, offset_x
    integer, parameter :: sx = threadsF%x
    integer, parameter :: sy = threadsF%y + 2*io + 1
    real(8), dimension(-(io-1):sx*sy-io), shared :: rho, u, v, p, tmp
    it = threadIdx%x
    jt = threadIdx%y
    i  = (blockIdx%x-1)*blockDim%x + it + 1
    j_base = (blockIdx%y-1)*blockDim%y
    offset_x = (it-1) * sy
    do jj = jt-io, threadsF%y+io+1, blockDim%y
      j = j_base + jj
      if (i >= 1 .and. i <= nx .and. j >= 1 .and. j <= ny) then
        idx = jj + offset_x
        rho(idx) = Q(i,1,j); u(idx) = Q(i,2,j)
          v(idx) = Q(i,3,j); p(idx) = Q(i,4,j); tmp(idx) = T(i,j)
      endif
    enddo
    call syncthreads()
    j = (blockIdx%y-1)*blockDim%y + jt
    if (io+1 <= j .and. j <= ny-(io+1) .and. i <= nx-1) then
      associate(vv => v)
      idx = jt + offset_x
      F(:,i-1,j) = KEEP(id_acc, &
                        rho(idx-io:idx+io+1), u(idx-io:idx+io+1), &
                          v(idx-io:idx+io+1), &
                         vv(idx-io:idx+io+1), p(idx-io:idx+io+1), &
                        tmp(idx-io:idx+io+1), Normal_y)
      end associate
    endif
  end subroutine calc_keep_y_in
end module calc_keep_kernel_internal
