#:include 'config.fypp'
!> Module containing 4th-order viscous flux computation kernels
!> Uses centered difference stencils to compute viscous stresses and heat flux
!> Generally more accurate but requires larger stencils than 2nd-order
module calc_visc4
  use mod_globals, only : gamma, R, Pr, Prt, dt, threadsEv, threadsFv
  use mod_constant, only : Cp, gamma_1, Cp_over_Pr, one_third, two_third, one_twelfth, id_visc
  use libm
  use load_smem_visc4
  implicit none
  private
  public calc_Ev4, calc_Fv4 
  real(8), parameter :: one_24 = 1.d0 / 24.d0 !< coefficient for 4th-order flux (1/24)
contains
  include 'calc_visc_me4_base.f90'

  !> CUDA Fortran kernel for 4th-order viscous flux in x direction
  !> High-order accurate computation of viscous stress and heat flux
  attributes(global) subroutine calc_Ev4(nx, ny, dx, dy, Q, T, mu, E)
    integer, intent(in), value                 :: nx             !< number of grid points in x direction
    integer, intent(in), value                 :: ny             !< number of grid points in y direction
    real(8), intent(in), device, contiguous    :: dx(nx-1)       !< inverse grid spacing in x (1/dx)
    real(8), intent(in), device, contiguous    :: dy(ny-1)       !< inverse grid spacing in y (1/dy)
    real(8), intent(in), device, contiguous    :: Q(nx,4,ny)     !< conservative variables
    real(8), intent(in), device, contiguous    :: T(nx,ny)       !< temperature at grid points
    real(8), intent(in), device, contiguous    :: mu(nx,ny)      !< molecular viscosity coefficient
    real(8), intent(inout), device, contiguous :: E(4,nx-1,ny-2) !< viscous flux components in x direction
    integer, parameter :: io_v = 2
    integer, parameter :: sx = threadsEv%x + 2*io_v + 1
    integer, parameter :: sy = threadsEv%y
    real(8), dimension(-(io_v-1):sx*sy-io_v), shared ::  u
    real(8), dimension(-(io_v-1):sx*sy-io_v), shared ::  v
    real(8), dimension(-(io_v-1):sx*sy-io_v), shared :: uy
    real(8), dimension(-(io_v-1):sx*sy-io_v), shared :: vy
    integer i, j, it, jt, ii, idx, offset_y
    real(8) :: txx, txy, utxx, vtxy, kTx
    it = threadIdx%x
    jt = threadIdx%y
    j  = (blockIdx%y-1)*blockDim%y + jt + 1
    offset_y = (jt-1)*sx
    call load_smem_visc4_x(it, jt, j, nx, ny, dy, Q, u, v, uy, vy)
    i  = (blockIdx%x-1)*blockDim%x + it
    idx = it + offset_y
    if (nx-1 < i .or. ny-1 < j) return
    if (3 <= i .and. i <= nx-3 .and. 3 <= j .and. j <= ny-2) then
      block
        real(8) :: mu3(3)
        mu3(:) = 0.0625d0 * (9.d0 * (mu(i-1:i+1,j) + mu(i:i+2,j)) - (mu(i-2:i,j) + mu(i+1:i+3,j)))
        block ! dQdx
          real(8) :: kTx3(3)
          kTx3(:) = Cp_over_Pr * mu3(:) * &
                    (1.125d0 * (-T(i-1:i+1,j) + T(i:i+2,j)) - (-T(i-2:i,j) + T(i+1:i+3,j)) * one_24) * dx(i)
          kTx     = flux4(kTx3(:))
        end block
        call calc_tau_straight(mu3, u(idx-2:idx+3), vy(idx-2:idx+3), dx(i), txx, utxx)
        call calc_tau_cross(mu3, v(idx-2:idx+3), uy(idx-2:idx+3), dx(i), txy, vtxy)
      end block
    else
      block
        real(8) mx, mux, mvx, muy, mvy
        mx  = 0.5d0 * (mu(i,j) + mu(i+1,j))
        kTx = Cp_over_Pr * mx * (-T(i,j) + T(i+1,j)) * dx(i)
        block
          real(8) :: my(2)
          my(1) = 0.25d0 * (mu(i,j-1) + mu(i,j  ) + mu(i+1,j-1) + mu(i+1,j  ))
          my(2) = 0.25d0 * (mu(i,j  ) + mu(i,j+1) + mu(i+1,j  ) + mu(i+1,j+1))
          muy = 0.25d0 * (my(1) * (-Q(i,2,j-1) + Q(i,2,j) - Q(i+1,2,j-1) + Q(i+1,2,j)) &
                        + my(2) * (-Q(i,2,j) + Q(i,2,j+1) - Q(i+1,2,j) + Q(i+1,2,j+1))) * dy(j)
          mvy = 0.25d0 * (my(1) * (-Q(i,3,j-1) + Q(i,3,j) - Q(i+1,3,j-1) + Q(i+1,3,j)) &
                        + my(2) * (-Q(i,3,j) + Q(i,3,j+1) - Q(i+1,3,j) + Q(i+1,3,j+1))) * dy(j)
        end block
        mux  = mx * (-u(idx) + u(idx+1)) * dx(i)
        mvx  = mx * (-v(idx) + v(idx+1)) * dx(i)
        txx  = two_third * (2.d0 * mux - mvy)
        txy  = muy + mvx
        utxx = 0.5d0 * (u(idx) + u(idx+1)) * txx
        vtxy = 0.5d0 * (v(idx) + v(idx+1)) * txy
      end block
    endif
    E(2,i,j-1) = E(2,i,j-1) - txx
    E(3,i,j-1) = E(3,i,j-1) - txy
    E(4,i,j-1) = E(4,i,j-1) - (utxx + vtxy + kTx)
  end subroutine calc_Ev4


  !> CUDA Fortran kernel for 4th-order viscous flux in y direction
  attributes(global) subroutine calc_Fv4(nx, ny, dy, dx, Q, T, mu, F)
    integer, intent(in), value                 :: nx             !< number of grid points in x direction
    integer, intent(in), value                 :: ny             !< number of grid points in y direction
    real(8), intent(in), device, contiguous    :: dy(ny-1)       !< inverse grid spacing in y (1/dy)
    real(8), intent(in), device, contiguous    :: dx(nx-1)       !< inverse grid spacing in x (1/dx)
    real(8), intent(in), device, contiguous    :: Q(nx,4,ny)     !< conservative variables
    real(8), intent(in), device, contiguous    :: T(nx,ny)       !< temperature at grid points
    real(8), intent(in), device, contiguous    :: mu(nx,ny)      !< molecular viscosity coefficient
    real(8), intent(inout), device, contiguous :: F(4,nx-2,ny-1) !< viscous flux components in y direction
    integer, parameter :: io_v = 2
    integer, parameter :: sx = threadsFv%x
    integer, parameter :: sy = threadsFv%y + 2*io_v + 1
    real(8), dimension(-(io_v-1):sx*sy-io_v), shared ::  u
    real(8), dimension(-(io_v-1):sx*sy-io_v), shared ::  v
    real(8), dimension(-(io_v-1):sx*sy-io_v), shared :: ux
    real(8), dimension(-(io_v-1):sx*sy-io_v), shared :: vx
    integer i, j, it, jt, jj, idx, offset_x
    real(8) :: tyx, tyy, utyx, vtyy, kTy
    it = threadIdx%x
    jt = threadIdx%y
    i  = (blockIdx%x-1)*blockDim%x + it + 1
    offset_x = (it-1)*sy
    call load_smem_visc4_y(it, jt, i, nx, ny, dx, Q, u, v, ux, vx)
    j  = (blockIdx%y-1)*blockDim%y + jt
    idx = jt + offset_x
    if (nx-1 < i .or. ny-1 < j) return
    if (3 <= i .and. i <= nx-2 .and. 3 <= j .and. j <= ny-3) then
      block
        real(8) :: mu3(3)
        mu3(:) = 0.0625d0 * (9.d0 * (mu(i,j-1:j+1) + mu(i,j:j+2)) - (mu(i,j-2:j) + mu(i,j+1:j+3)))
        block ! dQdy
          real(8) :: kTy3(3)
          kTy3(:) = Cp_over_Pr * mu3(:) * &
                    (1.125d0 * (-T(i,j-1:j+1) + T(i,j:j+2)) - (-T(i,j-2:j) + T(i,j+1:j+3)) * one_24) * dy(j)
          kTy     = flux4(kTy3(:))
        end block
        call calc_tau_straight(mu3, v(idx-2:idx+3), ux(idx-2:idx+3), dy(j), tyy, vtyy)
        call calc_tau_cross(mu3, u(idx-2:idx+3), vx(idx-2:idx+3), dy(j), tyx, utyx)
      end block
    else
      block
        real(8) my, muy, mvy, mux, mvx
        my  = 0.5d0 * (mu(i,j) + mu(i,j+1))
        kTy = Cp_over_Pr * my * (-T(i,j) + T(i,j+1)) * dy(j)
        block
          real(8) :: mx(2)
          mx(1) = 0.25d0 * (mu(i-1,j) + mu(i,  j) + mu(i-1,j+1) + mu(i,  j+1))
          mx(2) = 0.25d0 * (mu(i,  j) + mu(i+1,j) + mu(i,  j+1) + mu(i+1,j+1))
          mux = 0.25d0 * (mx(1) * (-Q(i-1,2,j) + Q(i,2,j) - Q(i-1,2,j+1) + Q(i,2,j+1)) &
                        + mx(2) * (-Q(i,2,j) + Q(i+1,2,j) - Q(i,2,j+1) + Q(i+1,2,j+1))) * dx(i)
          mvx = 0.25d0 * (mx(1) * (-Q(i-1,3,j) + Q(i,3,j) - Q(i-1,3,j+1) + Q(i,3,j+1)) &
                        + mx(2) * (-Q(i,3,j) + Q(i+1,3,j) - Q(i,3,j+1) + Q(i+1,3,j+1))) * dx(i)
        end block
        my  = 0.5d0 * (mu(i,j) + mu(i,j+1))
        kTy = Cp_over_Pr * my * (-T(i,j) + T(i,j+1)) * dy(j)
        muy  = my * (-u(idx) + u(idx+1)) * dy(j)
        mvy  = my * (-v(idx) + v(idx+1)) * dy(j)
        tyx  = muy + mvx
        tyy  = two_third * (2.d0 * mvy - mux)
        utyx = 0.5d0 * (u(idx) + u(idx+1)) * tyx
        vtyy = 0.5d0 * (v(idx) + v(idx+1)) * tyy
      end block
    endif
    F(2,i-1,j) = F(2,i-1,j) - tyx
    F(3,i-1,j) = F(3,i-1,j) - tyy
    F(4,i-1,j) = F(4,i-1,j) - (utyx + vtyy + kTy)
  end subroutine calc_Fv4
end module calc_visc4
