#:include 'config.fypp'
module calc_slau_kernel
  use mod_globals, only : gamma, threadsE, threadsF
  use mod_constant, only : over_gamma_1, id_slau
  use calc_muscl
  use calc_hybrid
  use libm
  implicit none
  private
  public calc_slau_x, calc_slau_y
  integer, parameter :: io = ${ORDER_IO}$

  interface SLAU
    module procedure SLAU1, HRSLAU2
  end interface SLAU
contains
  include 'calc_slau_2d.f90'

  attributes(global) subroutine calc_slau_x(nx, ny, Q, sensor, E)
    use mod_constant, only : Normal_x
    integer, intent(in), value                :: nx, ny
    real(8), intent(in), device, contiguous   :: Q(nx,4,ny)
    real(sp), intent(in), device, contiguous  :: sensor(nx,ny)
    real(8), intent(out), device, contiguous  :: E(4,nx-1,ny-2)
    integer i, j, it, jt, ii, i_base, idx, offset_y
    integer, parameter :: sx  = threadsE%x + 2*io + 1
    integer, parameter :: sy  = threadsE%y
    real(8), dimension(-(io-1):sx*sy-io), shared :: rho, u, v, p
    real(sp) fdx
#:if ORDER >= 4
    integer idx_r, offset_yr
    integer, parameter :: sxr = threadsE%x
    real(8), dimension(sxr*sy), shared :: rhor, ur, vr, pr
    real(8) rhol, ul, vl, pl
#:endif
    it = threadIdx%x
    jt = threadIdx%y
    j  = (blockIdx%y-1)*blockDim%y + jt + 1
    i_base   = (blockIdx%x-1)*blockDim%x
    offset_y = (jt-1) * sx
    do ii = it-io, threadsE%x+io+1, blockDim%x
      i = i_base + ii
      if (i >= 1 .and. i <= nx .and. j >= 1 .and. j <= ny) then
        idx = ii + offset_y
        rho(idx) = Q(i,1,j); u(idx) = Q(i,2,j)
          v(idx) = Q(i,3,j); p(idx) = Q(i,4,j)
      endif
    enddo
    call syncthreads()
    i = (blockIdx%x-1)*blockDim%x + it
    if (nx-1 < i .or. ny-1 < j) return
    idx = it + offset_y
#:if ORDER >= 4
    offset_yr = (jt-1) * sxr
    idx_r = it + offset_yr
#:endif
    fdx = 0.5_sp * (sensor(i,j) + sensor(i+1,j))
#:if ORDER == 6
    if (3 <= i .and. i <= nx-3) then
      call delta6(fdx, rho(idx-2:idx+3), rhol, rhor(idx_r))
      call delta6(fdx,   u(idx-2:idx+3),   ul,   ur(idx_r))
      call delta6(fdx,   v(idx-2:idx+3),   vl,   vr(idx_r))
      call delta6(fdx,   p(idx-2:idx+3),   pl,   pr(idx_r))
      fdx = wiggle_detector(p(idx-1:idx+2))
    elseif (2 <= i .and. i <= nx-2) then
      call delta4(fdx, rho(idx-1:idx+2), rhol, rhor(idx_r))
      call delta4(fdx,   u(idx-1:idx+2),   ul,   ur(idx_r))
      call delta4(fdx,   v(idx-1:idx+2),   vl,   vr(idx_r))
      call delta4(fdx,   p(idx-1:idx+2),   pl,   pr(idx_r))
      fdx = wiggle_detector(p(idx-1:idx+2))
    else
      rhol = rho(idx); rhor(idx_r) = rho(idx+1)
        ul =   u(idx);   ur(idx_r) =   u(idx+1)
        vl =   v(idx);   vr(idx_r) =   v(idx+1)
        pl =   p(idx);   pr(idx_r) =   p(idx+1)
       fdx = 1.0_sp
    endif
    associate(un1 => ul, un2 => ur(idx_r))
      call SLAU(id_slau, rhol, rhor(idx_r), ul, ur(idx_r), vl, vr(idx_r), &
                un1, un2, pl, pr(idx_r), Normal_x, fdx, &
                E(1,i,j-1), E(2,i,j-1), E(3,i,j-1), E(4,i,j-1))
    end associate
#:elif ORDER == 4
    if (2 <= i .and. i <= nx-2) then
      call delta4(fdx, rho(idx-1:idx+2), rhol, rhor(idx_r))
      call delta4(fdx,   u(idx-1:idx+2),   ul,   ur(idx_r))
      call delta4(fdx,   v(idx-1:idx+2),   vl,   vr(idx_r))
      call delta4(fdx,   p(idx-1:idx+2),   pl,   pr(idx_r))
      fdx = wiggle_detector(p(idx-1:idx+2))
    else
      rhol = rho(idx); rhor(idx_r) = rho(idx+1)
        ul =   u(idx);   ur(idx_r) =   u(idx+1)
        vl =   v(idx);   vr(idx_r) =   v(idx+1)
        pl =   p(idx);   pr(idx_r) =   p(idx+1)
       fdx = 1.0_sp
    endif
    associate(un1 => ul, un2 => ur(idx_r))
      call SLAU(id_slau, rhol, rhor(idx_r), ul, ur(idx_r), vl, vr(idx_r), &
                un1, un2, pl, pr(idx_r), Normal_x, fdx, &
                E(1,i,j-1), E(2,i,j-1), E(3,i,j-1), E(4,i,j-1))
    end associate
#:else
    associate(un1 => u(idx), un2 => u(idx+1))
      call SLAU(id_slau, rho(idx), rho(idx+1), u(idx), u(idx+1), v(idx), v(idx+1), &
                un1, un2, p(idx), p(idx+1), Normal_x, 1.0_sp, &
                E(1,i,j-1), E(2,i,j-1), E(3,i,j-1), E(4,i,j-1))
    end associate
#:endif
  end subroutine calc_slau_x


  attributes(global) subroutine calc_slau_y(nx, ny, Q, sensor, F)
    use mod_constant, only : Normal_y
    integer, intent(in), value                :: nx, ny
    real(8), intent(in), device, contiguous   :: Q(nx,4,ny)
    real(sp), intent(in), device, contiguous  :: sensor(nx,ny)
    real(8), intent(out), device, contiguous  :: F(4,nx-2,ny-1)
    integer i, j, it, jt, jj, j_base, idx, offset_x
    integer, parameter :: sx  = threadsF%x
    integer, parameter :: sy  = threadsF%y + 2*io + 1
    real(8), dimension(-(io-1):sx*sy-io), shared :: rho, u, v, p
    real(sp) fdy
#:if ORDER >= 4
    integer idx_r, offset_xr
    integer, parameter :: syr = threadsF%y
    real(8), dimension(sx*syr), shared :: rhor, ur, vr, pr
    real(8) rhol, ul, vl, pl
#:endif
    it = threadIdx%x
    jt = threadIdx%y
    i  = (blockIdx%x-1)*blockDim%x + it + 1
    j_base   = (blockIdx%y-1)*blockDim%y
    offset_x = (it-1) * sy
    do jj = jt-io, threadsF%y+io+1, blockDim%y
      j = j_base + jj
      if (i >= 1 .and. i <= nx .and. j >= 1 .and. j <= ny) then
        idx = jj + offset_x
        rho(idx) = Q(i,1,j); u(idx) = Q(i,2,j)
          v(idx) = Q(i,3,j); p(idx) = Q(i,4,j)
      endif
    enddo
    call syncthreads()
    j = (blockIdx%y-1)*blockDim%y + jt
    if (nx-1 < i .or. ny-1 < j) return
    idx = jt + offset_x
#:if ORDER >= 4
    offset_xr = (it-1) * syr
    idx_r = jt + offset_xr
#:endif
    fdy = 0.5_sp * (sensor(i,j) + sensor(i,j+1))
#:if ORDER == 6
    if (3 <= j .and. j <= ny-3) then
      call delta6(fdy, rho(idx-2:idx+3), rhol, rhor(idx_r))
      call delta6(fdy,   u(idx-2:idx+3),   ul,   ur(idx_r))
      call delta6(fdy,   v(idx-2:idx+3),   vl,   vr(idx_r))
      call delta6(fdy,   p(idx-2:idx+3),   pl,   pr(idx_r))
      fdy = wiggle_detector(p(idx-1:idx+2))
    elseif (2 <= j .and. j <= ny-2) then
      call delta4(fdy, rho(idx-1:idx+2), rhol, rhor(idx_r))
      call delta4(fdy,   u(idx-1:idx+2),   ul,   ur(idx_r))
      call delta4(fdy,   v(idx-1:idx+2),   vl,   vr(idx_r))
      call delta4(fdy,   p(idx-1:idx+2),   pl,   pr(idx_r))
      fdy = wiggle_detector(p(idx-1:idx+2))
    else
      rhol = rho(idx); rhor(idx_r) = rho(idx+1)
        ul =   u(idx);   ur(idx_r) =   u(idx+1)
        vl =   v(idx);   vr(idx_r) =   v(idx+1)
        pl =   p(idx);   pr(idx_r) =   p(idx+1)
       fdy = 1.0_sp
    endif
    associate(un1 => vl, un2 => vr(idx_r))
      call SLAU(id_slau, rhol, rhor(idx_r), ul, ur(idx_r), vl, vr(idx_r), &
                un1, un2, pl, pr(idx_r), Normal_y, fdy, &
                F(1,i-1,j), F(2,i-1,j), F(3,i-1,j), F(4,i-1,j))
    end associate
#:elif ORDER == 4
    if (2 <= j .and. j <= ny-2) then
      call delta4(fdy, rho(idx-1:idx+2), rhol, rhor(idx_r))
      call delta4(fdy,   u(idx-1:idx+2),   ul,   ur(idx_r))
      call delta4(fdy,   v(idx-1:idx+2),   vl,   vr(idx_r))
      call delta4(fdy,   p(idx-1:idx+2),   pl,   pr(idx_r))
      fdy = wiggle_detector(p(idx-1:idx+2))
    else
      rhol = rho(idx); rhor(idx_r) = rho(idx+1)
        ul =   u(idx);   ur(idx_r) =   u(idx+1)
        vl =   v(idx);   vr(idx_r) =   v(idx+1)
        pl =   p(idx);   pr(idx_r) =   p(idx+1)
       fdy = 1.0_sp
    endif
    associate(un1 => vl, un2 => vr(idx_r))
      call SLAU(id_slau, rhol, rhor(idx_r), ul, ur(idx_r), vl, vr(idx_r), &
                un1, un2, pl, pr(idx_r), Normal_y, fdy, &
                F(1,i-1,j), F(2,i-1,j), F(3,i-1,j), F(4,i-1,j))
    end associate
#:else
    associate(un1 => v(idx), un2 => v(idx+1))
      call SLAU(id_slau, rho(idx), rho(idx+1), u(idx), u(idx+1), v(idx), v(idx+1), &
                un1, un2, p(idx), p(idx+1), Normal_y, 1.0_sp, &
                F(1,i-1,j), F(2,i-1,j), F(3,i-1,j), F(4,i-1,j))
    end associate
#:endif
  end subroutine calc_slau_y
end module calc_slau_kernel
