#:set VISC          = 'NS'
#:set SCHEME        = 'Hybrid'
#:set ORDER         = 6
#:set TVD           = 'none'
#:set SLAU_VARIANT  = 'HRSLAU2'
#:set RESCALE       = False
#:set RESTART       = False
#:set RK            = 3
#:set BC_X          = True
#:set BC_Y          = True
#:set BC_Z          = False
#:set COMMZ         = False
#:set ORDER_IO = ORDER // 2 - 1
#:set OUTPUT_PRECISION = 4
#:set MPI = 'GPU'
#! set_bc takes (x, z, phi_l_gpu, phi_m_gpu, t_now) for the blowing/suction strip
#:set BC_FORCING = True
